### ISSUE TITLE
Cozy-stack install fails with message `Error: Could not find config file "cozy-admin-passphrase"`

### ISSUE THREAD

**Issue by halfpastfive** [cozy/cozy-stack#1311] opened 2018-03-31 19:09 UTC
While following [these steps](https://docs.cozy.io/fr/install/debian/) on debian 9, an error occurs during the `cozy-stack` package installation : 

`Error: Could not find config file "cozy-admin-passphrase"`

the package stays unconfigured, preventing the installation of cozy.

There  is a workaround to this issue ([found here](https://forum.cozy.io/t/probleme-install-cozy/5221/3)) : 

- create the file manually in `/etc/cozy/cozy-admin-passphrase`
- run the command :
` COZY_ADMIN_PASSPHRASE="${COZY_PASS}" cozy-stack config passwd /etc/cozy/cozy-admin-passphrase`

**Comment by aeris** [comment] 2018-03-31 19:39
This file is normally created [during setup](https://github.com/cozy/debian-cozy/blob/master/cozy-stack.postinst#L39-L40)
If it fails, can be caused by password with shell unsafe parameter or other error before this point.

**Comment by nono** [comment] 2018-04-16 07:11
Is it OK? Can we close this issue?

**Closed** 2018-04-27 14:36 UTC
