### ISSUE TITLE
Error: mkdir /home/cozy: permission denied

### ISSUE THREAD

**Issue by leolivier** [cozy/cozy-stack#866] opened 2017-07-30 09:20 UTC
Hi,
I followed the guide written by @clochix here: https://docs.cozy.io/en/install/manual/ 
Specifically, I created the cozy user without his home directory as explicitly mentioned in the guide:
```
adduser --system \
        --no-create-home \
        --shell /bin/bash \
        --group --gecos \
          "Cozy" cozy
```
Now, when I start cozy-serve with the command (from the guide):
```
sudo -b -u cozy sh -c '/usr/local/bin/cozy-stack serve \
     --log-level info \
     --host 0.0.0.0 >> /var/log/cozy/cozy.log 2>> /var/log/cozy/cozy-err.log'
```
I get the error of the title:
```::::::::::::::
/var/log/cozy/cozy-err.log
::::::::::::::
time="2017-07-30T11:01:39+02:00" level=info msg="[jobs] trigger @event(d76482f7dd2f93cfb2b7a18955017001): Starting trigger" nspace=mem-scheduler
Error: mkdir /home/cozy: permission denied
```
And the server stops.
I tried (to check): `sudo -b -u cozy sh -c ls` and it works fine.
I checked my /etc/cozy/cozy.yaml file and it does not contain any mention to this directory. However the /etc/passwd mentions /home/cozy as the home dir of the cozy user:
`cozy:x:126:136:Cozy,,,:/home/cozy:/bin/bash`

Any idea of what's going wrong? Should I still create the /home/cozy directory?

I'm running the latest cozy on raspbian jessie (and I got cozy "correctly" working from the basic install guide)
(BTW, `cozy-stack version` outputs a blank line, maybe I should open an issue for this?)

**Comment by leolivier** [comment] 2017-07-30 09:24
FYI, I created the home dir and it started working. Don't know why it needs it...
Either, you should fix this or change the doc...

**Comment by clochix** [comment] 2017-08-03 05:07
Thanks for reporting @leolivier. Seems to be a recent “regression”. Another user on Raspberry Pi is reporting that he had to create the home directory after updating `cozy-stack` to the last version.

@nono should I update the documentation, or do you want to investigate further to understand why this folder is now requested?

**Comment by nono** [comment] 2017-08-03 13:25
https://github.com/cozy/cozy-stack/commit/0c669bec4f14898a47ebb8fdac5d87b4a8f122e2It has been fixed with

**Closed by nono** 2017-08-03 13:25 UTC
